---
title: "Research"
---

```{r}
#| results: asis
#| message: false
#| warning: false
googlesheets4::gs4_deauth()
googlesheets4::gs4_auth(path = readr::read_file(Sys.getenv("GS4")))
id <- "10tpzG0y0drzzwbHRbzKdFInklf2eQzSX6iht7E7_BRw"
da <- googlesheets4::read_sheet(id)
```

```{r}
#| results: asis
#| message: false
#| warning: false
da |> 
  dplyr::filter(page == "research", type == "general") |> 
  with(glue::glue("{content}")) |> 
  cat(sep = "\n\n\n<hr>\n\n\n")
```

## Featured Work

```{r}
#| results: asis
#| message: false
#| warning: false
da |> 
  dplyr::filter(page == "index", type == "featured_work") |> 
  with(glue::glue("{content}")) |> 
  cat(sep = "\n\n\n<hr>\n\n\n")
```

## R&R

```{r}
#| results: asis
#| message: false
#| warning: false
da |> 
  dplyr::filter(page == "research", type == "rr") |> 
  with(glue::glue("{content}")) |> 
  cat(sep = "\n\n\n<hr>\n\n\n")
```

## Research Grants and Fellowships

```{r}
#| results: asis
#| message: false
#| warning: false
da |> 
  dplyr::filter(page == "research", type == "grants") |> 
  with(glue::glue("- {content}")) |> 
  cat(sep = "\n")
```

## Academic service

```{r}
#| results: asis
#| message: false
#| warning: false
da |> 
  dplyr::filter(page == "research", type == "service") |> 
  with(glue::glue("- {content}")) |> 
  cat(sep = "\n")
```


## Conference presentations and research seminars

```{r}
#| results: asis
#| message: false
#| warning: false
da |> 
  dplyr::filter(page == "research", type == "conference") |> 
  with(glue::glue("- {content}")) |> 
  cat(sep = "\n")
```